name: C++ CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.os }}@conda]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-2019, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install pixi [Linux&macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        curl -fsSL https://raw.githubusercontent.com/prefix-dev/pixi/main/install/install.sh | bash
        echo "$HOME/.pixi/bin" >> $GITHUB_PATH

    - name: Install pixi [Windows]
      if: contains(matrix.os, 'windows')
      shell: pwsh
      run: |
        iwr -useb https://raw.githubusercontent.com/prefix-dev/pixi/main/install/install.ps1 | iex

    - name: Build and Run
      run: |
        pixi run start
