name: C++ CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.os }}@conda]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-2019, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: prefix-dev/setup-pixi@v0.4.1
      with:
        cache: true

    - name: Build and Run
      shell: bash -l {0}
      run: | 
        # Check version of pixi actually used
        pixi --version
        # Workaround for https://github.com/prefix-dev/pixi/issues/122
        pixi run build
        pixi run onnx-cpp-benchmark --help
